parameters:
#    cantata_main.example.class: Cantata\MainBundle\Example

services:
#    cantata_main.example:
#        class: %cantata_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
