cantata_temp:
    type:     rest
    resource: Cantata\MainBundle\Controller\RestTempController

post:
    resource: "@CantataMainBundle/Controller/MainController.php"
    type:     annotation

cantata_main:
    resource: "@CantataMainBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


