cantata_temp:
    type:     rest
    resource: Cantata\MainBundle\Controller\RestTempController

post:
    resource: "@CantataMainBundle/Controller/MainController.php"
    type:     annotation

cantata_main:
    resource: "@CantataMainBundle/Resources/config/routing.yml"
    prefix:   /


